# Generated by Django 4.0.4 on 2022-05-15 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import khabari.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('likes', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OtpRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(blank=True, choices=[('Phone', 'Phone'), ('E_Mail', 'Email')], default='Phone', max_length=12)),
                ('receiver', models.CharField(max_length=10)),
                ('password', models.CharField(default=khabari.models.otp_generate, max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=128)),
                ('like', models.IntegerField(default=0)),
                ('news_text', models.TextField(blank=True, null=True)),
                ('news_image', models.ImageField(default='', upload_to='khabari/static')),
                ('video', models.FileField(default='', upload_to='rename_and_path')),
                ('news_type', models.CharField(blank=True, choices=[('Social', 'social'), ('Economy', 'economy'), ('Politic', 'politic'), ('Picture', 'picture'), ('International', 'international'), ('Family', 'family'), ('Media', 'media'), ('State', 'state'), ('Culture', 'culture'), ('Sport', 'sport')], max_length=128, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Published', 'published'), ('Draft', 'draft')], default='draft', max_length=10)),
                ('cm_likes', models.ManyToManyField(blank=True, related_name='likes_comments', through='khabari.Comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='khabari.newspage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newscomments', to='khabari.newspage'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercomments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('news', 'user')},
        ),
    ]
