# Generated by Django 4.0.4 on 2022-05-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khabari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='news_type',
            field=models.CharField(blank=True, choices=[('Culture', 'culture'), ('Economy', 'economy'), ('Sport', 'sport'), ('Family', 'family'), ('State', 'state'), ('Picture', 'picture'), ('International', 'international'), ('Politic', 'politic'), ('Social', 'social'), ('Media', 'media')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('Published', 'published')], default='draft', max_length=10),
        ),
    ]
