# Generated by Django 4.0.1 on 2022-04-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khabari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='cover',
            field=models.ImageField(default='', upload_to='khabari/static'),
        ),
    ]
