# Generated by Django 4.0.4 on 2022-05-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khabari', '0002_alter_newspage_news_type_alter_newspage_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='genre',
        ),
        migrations.AlterField(
            model_name='newspage',
            name='news_image',
            field=models.ImageField(default='static/pic.jpg', upload_to='khabari/static'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='news_type',
            field=models.CharField(blank=True, choices=[('Economy', 'economy'), ('Social', 'social'), ('Media', 'media'), ('State', 'state'), ('International', 'international'), ('Politic', 'politic'), ('Sport', 'sport'), ('Family', 'family'), ('Culture', 'culture'), ('Picture', 'picture')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='video',
            field=models.FileField(default='static/pic.jpg', upload_to='khabari/static'),
        ),
    ]
