# Generated by Django 4.0.4 on 2022-05-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khabari', '0003_delete_category_remove_newspage_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='news_type',
            field=models.CharField(blank=True, choices=[('Economy', 'economy'), ('Sport', 'sport'), ('Family', 'family'), ('Culture', 'culture'), ('Social', 'social'), ('Media', 'media'), ('International', 'international'), ('Politic', 'politic'), ('State', 'state'), ('Picture', 'picture')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='status',
            field=models.CharField(choices=[('Published', 'published'), ('Draft', 'draft')], default='draft', max_length=10),
        ),
    ]
