# Generated by Django 4.0.1 on 2022-04-22 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('khabari', '0003_alter_newspage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='newspage',
            old_name='cover',
            new_name='news_image',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='rate',
        ),
        migrations.AddField(
            model_name='newspage',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes_newspage', through='khabari.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='rating_comments', through='khabari.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='status',
            field=models.CharField(choices=[('Published', 'published'), ('Draft', 'draft')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='like',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_NewsPage', to='khabari.newspage'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_NewsPage', to=settings.AUTH_USER_MODEL),
        ),
    ]
