# Generated by Django 4.0.1 on 2022-04-24 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('khabari', '0004_like_rename_cover_newspage_news_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspage',
            old_name='like',
            new_name='news_like',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='ratings',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newspage',
            name='cm_likes',
            field=models.ManyToManyField(blank=True, related_name='likes_comments', through='khabari.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='khabari.newspage'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('Published', 'published')], default='draft', max_length=10),
        ),
    ]
