# Generated by Django 4.0.4 on 2022-05-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khabari', '0004_alter_newspage_news_type_alter_newspage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='has_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newspage',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newspage',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='news_type',
            field=models.CharField(blank=True, choices=[('Family', 'family'), ('Social', 'social'), ('Picture', 'picture'), ('Media', 'media'), ('International', 'international'), ('Politic', 'politic'), ('Culture', 'culture'), ('State', 'state'), ('Sport', 'sport'), ('Economy', 'economy')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='khabari/static'),
        ),
    ]
