# Generated by Django 4.0.1 on 2022-04-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khabari', '0005_rename_like_newspage_news_like_remove_comment_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='status',
            field=models.CharField(choices=[('Published', 'published'), ('Draft', 'draft')], default='draft', max_length=10),
        ),
    ]
